### ISSUE TITLE
关于bounding boxes特征

### ISSUE THREAD

**Issue by peixinlei** [LgQu/CAMERA#2]
作者您好，

首先感谢您开源这个有意义并且十分有趣的工作。我在复现的过程中发现了一个问题，请您解答一下：

我down了您提供的f30k数据集的bounding boxes特征和VSRN作者Kungpeng Li提供的bounding boxes特征，发现您们的region特征是一样的，但是bounding boxes特征是不同的，我觉得这可能有问题，不知道您是否可以为我解答一下。

再次感谢。

**Comment by LgQu** [comment]
您好， 

感谢您对我们工作的关注。关于f30k的bounding boxes信息，我们当时重新跑的bottom-up attention提取的，可能由于一些版本或框架的原因，数值上与VSRN的bounding boxes信息有微小的差距。建议您将bounding boxes在图像上画出来，进一步check一下，谢谢。
